TwitchEmotes:
  # - "name,unicode,source[TWITCH,DISCORD]"
  - "rudeBonk,\ue000,TWITCH"
  - "rudeCrime,\ue001,TWITCH"
  - "rudeDude,\ue002,TWITCH"
  - "rudeElle,\ue003,TWITCH"
  - "rudeEvil,\ue004,TWITCH"
  - "rudeRip,\ue005,TWITCH"

  - "rudeHi,\ue006,TWITCH"
  - "rudeHmm,\ue007,TWITCH"
  - "rudeHuh,\ue008,TWITCH"
  - "rudeHype,\ue009,TWITCH"
  - "rudeIdea,\ue00A,TWITCH"
  - "rudeShook,\ue00B,TWITCH"

  - "rudeJerry,\ue00C,TWITCH"
  - "rudeLove,\ue00D,TWITCH"
  - "rudeLUL,\ue00E,TWITCH"
  - "rudeNom,\ue00F,TWITCH"
  - "rudeOhno,\ue010,TWITCH"
  - "rudeThump,\ue011,TWITCH"

  - "rudeOmega,\ue012,TWITCH"
  - "rudeOmg,\ue013,TWITCH"
  - "rudeOri,\ue014,TWITCH"
  - "rudeOrier,\ue015,TWITCH"
  - "rudeOriest,\ue016,TWITCH"
  - "rudeWoah,\ue017,TWITCH"

  - "rudeOrimega,\ue018,TWITCH"
  - "rudePeek,\ue019,TWITCH"
  - "rudePls,\ue01A,TWITCH"
  - "rudePolice,\ue01B,TWITCH"
  - "rudeQueen,\ue01C,TWITCH"
  - "rudeZzz,\ue01D,TWITCH"

  - "rudeAus,\ue022,TWITCH"

BTTVEmotes:
  - "KEKW,\ue021,BTTV"
  - "rudeAyy,\ue023,BTTV"
  - "rudeSon,\ue024,BTTV"

OtherEmotes:
  - "flag_au,\ue01F,OTHER"
  - "flag_nz,\ue020,OTHER"